# Generated by Django 5.0.2 on 2025-08-04 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('circuit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('length_km', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('debut_year', models.IntegerField()),
                ('stats', models.CharField(max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('round_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.circuit')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('points', models.FloatField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.race')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='current_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
    ]
